export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILURE = "FETCH_SCHEDULE_FAILURE";

export const SCHEDULE_FOLLOW_REQUEST = "SCHEDULE_FOLLOW_REQUEST";
export const SCHEDULE_FOLLOW_SUCCESS = "SCHEDULE_FOLLOW_SUCCESS";
export const SCHEDULE_FOLLOW_FAILURE = "SCHEDULE_FOLLOW_FAILURE";

export const SCHEDULE_ADD_REQUEST = "SCHEDULE_ADD_REQUEST";
export const SCHEDULE_ADD_SUCCESS = "SCHEDULE_ADD_SUCCESS";
export const SCHEDULE_ADD_FAILURE = "SCHEDULE_ADD_FAILURE";

export const SCHEDULE_MODAL_SHOW = "SCHEDULE_MODAL_SHOW";
export const SCHEDULE_MODAL_HIDE = "SCHEDULE_MODAL_HIDE";
