export const ME_REQUEST = "ME_REQUEST";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAILURE = "ME_FAILURE";

export const ME_PROJECTS_REQUEST = "ME_PROJECTS_REQUEST";
export const ME_PROJECTS_SUCCESS = "ME_PROJECTS_SUCCESS";
export const ME_PROJECTS_FAILURE = "ME_PROJECTS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNUP_SOCIAL_REQUEST = "SIGNUP_SOCIAL_REQUEST";
export const SIGNUP_SOCIAL_SUCCESS = "SIGNUP_SOCIAL_SUCCESS";
export const SIGNUP_SOCIAL_FAILURE = "SIGNUP_SOCIAL_FAILURE";

export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAILURE = "CONFIRM_EMAIL_FAILURE";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";
export const PASSWORD_RESET_CONFIRM_REQUEST = "PASSWORD_RESET_CONFIRM_REQUEST";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAILURE = "PASSWORD_RESET_CONFIRM_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SOCIAL_APPS_REQUEST = "SOCIAL_APPS_REQUEST";
export const SOCIAL_APPS_SUCCESS = "SOCIAL_APPS_SUCCESS";
export const SOCIAL_APPS_FAILURE = "SOCIAL_APPS_FAILURE";

export const SOCIAL_APPS_VALIDATE_REQUEST = "SOCIAL_APPS_VALIDATE_REQUEST";
export const SOCIAL_APPS_VALIDATE_SUCCESS = "SOCIAL_APPS_VALIDATE_SUCCESS";
export const SOCIAL_APPS_VALIDATE_FAILURE = "SOCIAL_APPS_VALIDATE_FAILURE";

export const SIGNUP_STEP_0_REQUEST = "SIGNUP_STEP_0_REQUEST";
export const SIGNUP_STEP_1_REQUEST = "SIGNUP_STEP_1_REQUEST";

export const SIGNUP_STEP_SET_EMAIL = "SIGNUP_STEP_SET_EMAIL";
export const SIGNUP_STEP_SET_PASSWORD = "SIGNUP_STEP_SET_PASSWORD";
export const SIGNUP_STEP_SET_PASS_CONFIRM = "SIGNUP_STEP_SET_PASS_CONFIRM";
export const SIGNUP_STEP_SET_USERNAME = "SIGNUP_STEP_SET_USERNAME";
export const SIGNUP_STEP_SET_ROLE = "SIGNUP_STEP_SET_ROLE";
export const SIGNUP_STEP_SET_SKYPE = "SIGNUP_STEP_SET_SKYPE";
export const SIGNUP_STEP_SET_HANGOUTS = "SIGNUP_STEP_SET_HANGOUTS";
export const SIGNUP_STEP_SET_WANT_LEARN = "SIGNUP_STEP_SET_WANT_LEARN";
export const SIGNUP_STEP_SET_CONFIRM_EMAIL = "SIGNUP_STEP_SET_CONFIRM_EMAIL";
export const SET_PASSWORD_RESET_EMAIL = "SET_PASSWORD_RESET_EMAIL";

export const SET_LOGIN_FORM_ERROR = "SET_LOGIN_FORM_ERROR";
export const CLEAR_LOGIN_FORM_ERROR = "CLEAR_LOGIN_FORM_ERROR";
export const SET_SIGNUP_FORM_ERROR = "SET_SIGNUP_FORM_ERROR";
export const CLEAR_SIGNUP_FORM_ERROR = "CLEAR_SIGNUP_FORM_ERROR";
export const SET_SIGNUP_STEP_0_ERROR = "SET_SIGNUP_STEP_0_ERROR";
export const CLEAR_SIGNUP_STEP_0_ERROR = "CLEAR_SIGNUP_STEP_0_ERROR";
export const SET_SIGNUP_STEP_1_ERROR = "SET_SIGNUP_STEP_1_ERROR";
export const CLEAR_SIGNUP_STEP_1_ERROR = "CLEAR_SIGNUP_STEP_1_ERROR";
export const SET_SIGNUP_STEP_2_ERROR = "SET_SIGNUP_STEP_2_ERROR";
export const CLEAR_SIGNUP_STEP_2_ERROR = "CLEAR_SIGNUP_STEP_2_ERROR";
export const SET_SIGNUP_STEP_3_ERROR = "SET_SIGNUP_STEP_3_ERROR";
export const CLEAR_SIGNUP_STEP_3_ERROR = "CLEAR_SIGNUP_STEP_3_ERROR";
export const SET_SIGNUP_STEP_4_ERROR = "SET_SIGNUP_STEP_4_ERROR";
export const CLEAR_SIGNUP_STEP_4_ERROR = "CLEAR_SIGNUP_STEP_4_ERROR";
export const SET_CONFIRM_EMAIL_ERROR = "SET_CONFIRM_EMAIL_ERROR";
export const CLEAR_CONFIRM_EMAIL_ERROR = "CLEAR_CONFIRM_EMAIL_ERROR";
export const SET_PASSWORD_RESET_ERROR = "SET_PASSWORD_RESET_ERROR";
export const CLEAR_PASSWORD_RESET_ERROR = "CLEAR_PASSWORD_RESET_ERROR";

export const LOGIN_SUCCESS_URL = "/live";
export const SIGNUP_SUCCESS_URL = "/live";
export const LOGOUT_SUCCESS_URL = "/live";
export const SIGNUP_STEP_ERROR_URL = "/signup";

export const CLEAR_SIGNUP_STEPS = "CLEAR_SIGNUP_STEPS";
export const CLEAR_CONFIRM_EMAIL = "CLEAR_CONFIRM_EMAIL";
export const CLEAR_SIGNUP_SOCIAL_ERROR = "CLEAR_SIGNUP_SOCIAL_ERROR";

export const SIGNUP_SOCIAL_ERRORS = {
  EMAIL_IS_ALREADY_REGISTERED: {
    type: "EMAIL_IS_ALREADY_REGISTERED",
    text: "User with this email is already exist"
  },
  SOCIAL_ACCOUNT_IS_NOT_CONNECTED: {
    type: "SOCIAL_ACCOUNT_IS_NOT_CONNECTED",
    text: "Account is not connected to any user"
  },
  DEFAULT: {
    type: "DEFAULT",
    text: "Something went wrong"
  }
};
