export const FETCH_LIVE_PROJECTS_REQUEST = "FETCH_LIVE_PROJECTS_REQUEST";
export const FETCH_LIVE_PROJECTS_SUCCESS = "FETCH_LIVE_PROJECTS_SUCCESS";
export const FETCH_LIVE_PROJECTS_FAILURE = "FETCH_LIVE_PROJECTS_FAILURE";

export const FETCH_UPCOMING_PROJECTS_REQUEST =
  "FETCH_UPCOMING_PROJECTS_REQUEST";
export const FETCH_UPCOMING_PROJECTS_SUCCESS =
  "FETCH_UPCOMING_PROJECTS_SUCCESS";
export const FETCH_UPCOMING_PROJECTS_FAILURE =
  "FETCH_UPCOMING_PROJECTS_FAILURE";
