export const FETCH_PROJECT_REQUESTS_REQUEST = "FETCH_PROJECT_REQUESTS_REQUEST";
export const FETCH_PROJECT_REQUESTS_SUCCESS = "FETCH_PROJECT_REQUESTS_SUCCESS";
export const FETCH_PROJECT_REQUESTS_FAILURE = "FETCH_PROJECT_REQUESTS_FAILURE";

export const PROJECT_REQUESTS_VOTE_REQUEST = "PROJECT_REQUESTS_VOTE_REQUEST";
export const PROJECT_REQUESTS_VOTE_SUCCESS = "PROJECT_REQUESTS_VOTE_SUCCESS";
export const PROJECT_REQUESTS_VOTE_FAILURE = "PROJECT_REQUESTS_VOTE_FAILURE";

export const PROJECT_REQUESTS_ADD_REQUEST = "PROJECT_REQUESTS_ADD_REQUEST";
export const PROJECT_REQUESTS_ADD_SUCCESS = "PROJECT_REQUESTS_ADD_SUCCESS";
export const PROJECT_REQUESTS_ADD_FAILURE = "PROJECT_REQUESTS_ADD_FAILURE";

export const PROJECT_REQUESTS_MODAL_SHOW = "PROJECT_REQUESTS_MODAL_SHOW";
export const PROJECT_REQUESTS_MODAL_HIDE = "PROJECT_REQUESTS_MODAL_HIDE";
