export const FETCH_NON_EDU_PROJECTS_REQUEST = "FETCH_NON_EDU_PROJECTS_REQUEST";
export const FETCH_NON_EDU_PROJECTS_SUCCESS = "FETCH_NON_EDU_PROJECTS_SUCCESS";
export const FETCH_NON_EDU_PROJECTS_FAILURE = "FETCH_NON_EDU_PROJECTS_FAILURE";
